carga/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from carga import views, models

app_name = "carga"

urlpatterns = [
	#path("imprimir/<pk>", views.ImprimirLegacyPoliza.as_view(), name="imprimir-poliza"),
	#path("update/<pk>", views.UpdateLegacyPoliza.as_view(), name="update"),
	#path("crear/poliza/", views.CrearLegacyPoliza.as_view(), name="legacy-crear-poliza"),
	path("crear/empresa/", views.CrearEmpresa.as_view(), name="crear-empresa"),
	path("crear/empresa/<pk>", views.UpdateEmpresa.as_view(), name="update-empresa"),
]
certificado_patterns = [
	path("crear/certificado/", views.CrearCertificado.as_view(), name="crear-certificado"),
	path("crear/certificado/<pk>", views.UpdateCertificado.as_view(), name="update-certificado"),
	path("crear/certificado/detalle/<pk>", views.CertificadoView.as_view(), name="detalle-certificado")
]
obra_patterns = [
	path("crear/obra/", views.CrearObra.as_view(), name="crear-obra"),
	path("crear/obra/<pk>", views.UpdateObra.as_view(), name="update-obra"),
	path("crear/obra/estado/<pk>", views.EstadoObra.as_view(), name = "estado-obra"),
]
poliza_patterns = [
	path("crear/poliza/", views.CrearPoliza.as_view(), name="crear-poliza"),
	path("crear/poliza/<pk>", views.UpdatePoliza.as_view(), name="update-poliza"),
	path("crear/poliza/estado/<pk>", views.EstadoPoliza.as_view(), name="estado-poliza"),
]
movimiento_patterns = [
	path("crear/poliza/movimiento/", views.CrearPolizaMovimiento.as_view(), name="crear-poliza-movimiento"),
	path("crear/poliza/movimiento/<pk>", views.UpdatePolizaMovimiento.as_view(), name="update-poliza-movimiento"),
	path("crear/poliza/movimiento/imprimir/<pk>", views.ImprimirPolizaMovimiento.as_view(), name="imprimir-poliza-movimiento"),

]
legacy_patterns = [
	path("crear/legacy_poliza/", views.CrearLegacyPoliza.as_view(), name="legacy-crear-poliza"),
	path("legacy_imprimir/<pk>", views.ImprimirLegacyPoliza.as_view(), name="legacy-imprimir-poliza"),
	path("legacy_update/<pk>", views.UpdateLegacyPoliza.as_view(), name="legacy-update-poliza"),
]

urlpatterns += certificado_patterns
urlpatterns += legacy_patterns
urlpatterns += poliza_patterns
urlpatterns += movimiento_patterns
urlpatterns += obra_patterns

carga/models.py
from datetime import datetime
from re import T
from wsgiref.validate import validator
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

# Create your models here.

class Receptor(models.Model):
    class Meta:
        verbose_name = "Receptor"
        verbose_name_plural = "Receptores"
    
    receptor_nombre = models.CharField("Receptor", max_length=100)

    def __str__(self):
        return self.receptor_nombre

class Area(models.Model):
    class Meta:
        verbose_name  = "Area"
        verbose_name_plural = "Areas"
    
    area_nombre = models.CharField("Area", max_length=50)

    def __str__(self):
        return self.area_nombre

class Aseguradora(models.Model):
    class Meta:
        verbose_name = "Aseguradora"
        verbose_name_plural = "Aseguradoras"
    
    aseguradora_nombre = models.CharField("Nombre Empresa Aeguradora", max_length=255)

    def __str__(self):
        return self.aseguradora_nombre

class Empresa(models.Model):
    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"
    
    empresa_nombre          = models.CharField("Nombre Empresa Tomadora:", max_length=255)
    empresa_cuit            = models.CharField("CUIT:", max_length=11, blank=True, null=True)
    empresa_titular_titulo  = models.CharField("Titulo Representante:", max_length=40, blank=True, null=True)
    empresa_titular_nombre  = models.CharField("Titular de la Empresa", max_length=140, blank=True, null=True)
    empresa_titular_dni     = models.DecimalField("DNI:", max_digits=9, decimal_places=0, blank=True, null=True)
    empresa_direccion       = models.CharField("Dirección de la Empresa", max_length=255, blank=True, null=True)
    empresa_inscripcion     = models.CharField("Inscripción:", max_length=500, blank=True, null=True)
    empresa_correo_p        = models.EmailField("Dirección de Correo Primaria:", blank=True, null=True)
    empresa_correo_s        = models.EmailField("Dirección de Correo Alternativa:", blank=True, null=True)


    def __str__(self):
        return self.empresa_nombre

class Poliza(models.Model):
    CONCEPTO = (
        ("C", "Garantía de Ejecución de Contrato"),
        ("F", "Garantía de Sustitución de Fondo de Reparo"),
        ("A", "Garantía de Anticipo Financiero")
    )

    class Meta:
        constraints = [models.UniqueConstraint(fields=["poliza_fecha", "poliza_numero", "poliza_aseguradora","poliza_tomador"], name="poliza-constraint")]
        verbose_name = "Póliza"
        verbose_name_plural = "Pólizas"
    
    poliza_fecha = models.DateField("Fecha")
    poliza_expediente = models.CharField("Expediente", max_length=18)
    poliza_numero = models.IntegerField("Número de Póliza")
    poliza_concepto = models.CharField("Concepto", max_length=1, choices=CONCEPTO)
    poliza_anexo = models.CharField("Anexo de Póliza", max_length=40, blank=True, null=True)
    poliza_recibo = models.CharField("Número de Recibo", max_length=100)
    poliza_aseguradora = models.ForeignKey("Aseguradora", on_delete=models.CASCADE)
    poliza_tomador = models.ForeignKey("Empresa", on_delete=models.CASCADE)
    poliza_obra = models.ForeignKey("Obra", on_delete=models.CASCADE)
    poliza_monto_pesos = models.DecimalField("Monto Sustituido en Pesos", max_digits=15, decimal_places=2, blank=True, null=True, validators=[MinValueValidator(0)])
    poliza_monto_uvi = models.DecimalField("Monto Sustituido en UVI", max_digits=15, decimal_places=2, blank=True, null=True, validators=[MinValueValidator(0)])
    poliza_creador = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, editable=False)
    poliza_editor = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="poliza_editor", editable=False)
    
    def __str__(self):
        return f"{self.poliza_numero} - {self.poliza_aseguradora.aseguradora_nombre} - {self.poliza_obra.obra_nombre} - {self.poliza_tomador.empresa_nombre} "

    def get_absolute_url(self):
        return f"/polizas/update/{self.id}"

class Poliza_Movimiento(models.Model):
    class Meta:
        verbose_name = "Poliza_Movimiento"
        verbose_name_plural = "Polizas_Movimiento"
    
    poliza_movimiento_fecha     = models.DateField("Fecha")
    poliza_movimiento_receptor  = models.ForeignKey("Receptor", on_delete=models.CASCADE)
    poliza_movimiento_area      = models.ForeignKey("Area", on_delete=models.CASCADE)
    poliza_movimiento_editor    = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, editable=False)
    poliza_movimiento_numero    = models.ForeignKey("Poliza", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.poliza_movimiento_numero} - {self.poliza_movimiento_area} - ({self.poliza_movimiento_fecha})"

class LegacyPoliza(models.Model):
    CONCEPTO = (
        ("C", "Garantía de Ejecución de Contrato"),
        ("F", "Garantía de Sustitución de Fondo de Reparo"),
        ("A", "Garantía de Anticipo Financiero")
    )

    class Meta:
        constraints = [models.UniqueConstraint(fields=["legacy_poliza_expediente", "legacy_poliza_fecha", "legacy_poliza_numero", "legacy_poliza_aseguradora","legacy_poliza_receptor"], name="legacy-poliza-constraint")]
        verbose_name = "Legacy_Póliza"
        verbose_name_plural = "Legacy_Pólizas"

    legacy_poliza_fecha            = models.DateField("Fecha")
    legacy_poliza_expediente       = models.CharField("Número de Expediente", max_length=17)
    legacy_poliza_receptor         = models.ForeignKey("Receptor", on_delete=models.CASCADE)
    legacy_poliza_area             = models.ForeignKey("Area", on_delete=models.CASCADE)
    legacy_poliza_numero           = models.IntegerField("Número de Póliza")
    legacy_poliza_concepto         = models.CharField("Concepto", max_length=1, choices=CONCEPTO)
    legacy_poliza_anexo            = models.CharField("Anexo de póliza", max_length=40, blank=True, null=True)
    legacy_poliza_recibo           = models.CharField("Número de Recibo", max_length=100)
    legacy_poliza_aseguradora      = models.ForeignKey("Aseguradora", on_delete=models.CASCADE)
    legacy_poliza_tomador          = models.ForeignKey("Empresa", on_delete=models.CASCADE)
    legacy_poliza_obra_nombre      = models.TextField("Obra")
    legacy_poliza_obra_convenio    = models.CharField("Convenio", max_length=50, blank=True, null=True)
    legacy_poliza_obra_expediente  = models.CharField("Número de Expediente de la Obra", max_length=17, blank=True, null=True)
    legacy_poliza_monto_pesos      = models.DecimalField("Monto Sustituido Pesos", max_digits=12, decimal_places=2, blank=True, null=True, validators=[MinValueValidator(0)])
    legacy_poliza_monto_uvi        = models.DecimalField("Monto Sustituido UVI", max_digits=12, decimal_places=2, blank=True, null=True, validators=[MinValueValidator(0)])
    legacy_poliza_creador          = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, editable=False)
    legacy_poliza_editor           = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="legacy_poliza_editor", editable=False)
    
class Programa(models.Model):
    class Meta:
        verbose_name = "Progrma"
        verbose_name_plural = "Programas"
    
    programa_nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.programa_nombre

class Departamento(models.Model):
	class Meta:
		ordering			= ["departamento_nombre"]
		verbose_name_plural = "Departamentos"

	id					= models.IntegerField(unique=True, primary_key=True)
	departamento_nombre = models.TextField("Nombre Departamento")
	
	def __str__(self):
		return self.departamento_nombre

class Localidad(models.Model):
	class Meta:
		ordering			= ["localidad_nombre"]
		verbose_name_plural = "Localidades"

	localidad_nombre		= models.TextField("Nombre Localidad")
	id                      = models.IntegerField(unique=True, primary_key=True) 
	localidad_centroide_lat	= models.DecimalField(max_digits=15, decimal_places=13,blank=True, null=True)
	localidad_centroide_lon	= models.DecimalField(max_digits=15, decimal_places=13,blank=True, null=True)
	localidad_funcion       = models.CharField(max_length=40,blank=True, null=True)
	localidad_departamento	= models.ForeignKey("Departamento", on_delete=models.RESTRICT)
	localidad_municipio     = models.ForeignKey("Municipio", on_delete=models.CASCADE)

	def __str__(self):
		return self.localidad_nombre
		# return "{} - Departamento {}".format(self.localidad_nombre, self.localidad_departamento)

class Municipio(models.Model):
	class Meta:
		ordering 			= ["municipio_nombre"]
		verbose_name_plural = "Municipios"
	
	municipio_nombre        = models.CharField(max_length=40)
	id                      = models.IntegerField(unique=True, primary_key=True)
	municipio_departamento  = models.ForeignKey("Departamento", on_delete=models.CASCADE)
	
	def __str__(self):
		return self.municipio_nombre

class Obra(models.Model):
    COMPULSA = (
        ("L", "Licitación Pública"),
        ("P", "Licitación Privada"),
        ("C", "Concurso de Precios"),
        ("D", "Contratación Directa")
    )
    
    class Meta:
        # constraints = [models.UniqueConstraint(fields=["obra_nombre", "obra_empresa", "obra_convenio","obra_programa"], name="obra-constraint")]
        verbose_name = "Obra"
        verbose_name_plural = "Obras"
    
    obra_nombre			    = models.TextField("Nombre de la Obra tal como figura en el contrato")
    obra_soluciones		    = models.DecimalField("Cantidad de soluciones", max_digits=4, decimal_places=0, null=True, blank=True)
    obra_empresa		    = models.ForeignKey("Empresa", on_delete=models.CASCADE, verbose_name="Obra_Empresa")
    obra_localidad		    = models.ForeignKey("Localidad", on_delete=models.CASCADE)

carga/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django_select2 import forms as s2forms
from carga import models
from datetime import datetime
import locale

def dateconverter(value):
	locale.setlocale(locale.LC_TIME, "es_AR.UTF-8")
	value = datetime.strptime(value, "%b/%y").date()
	value = "{0:%d}-{0:%m}-{0:%Y}".format(value,"day","month","year")
	print(value)
	return value

class LoginForm(AuthenticationForm):
	def confirm_login_allowed(self, user):
		pass

class EmpresaWidget(s2forms.ModelSelect2Widget):
	search_fields = [
		"empresa_nombre__icontains"
	]

class PolizaForm(forms.ModelForm):
	CONCEPTO = (
		("C", "Garantía de Ejecución de Contrato"),
		("F", "Garantía de Sustitución de Fondo de Reparo"),
		("A", "Garantía de Anticipo Financiero")
	)
	poliza_fecha	= forms.DateField(input_formats=["%d/%m/%Y"], localize=True)
	poliza_concepto = forms.ChoiceField(choices=CONCEPTO)
	
	class Meta:
		model = models.Poliza
		fields = "__all__"
		widgets = {
			"poliza_tomador" : EmpresaWidget
		}
		
class LegacyPolizaForm(forms.ModelForm):
	CONCEPTO = (
        ("C", "Garantía de Ejecución de Contrato"),
        ("F", "Garantía de Sustitución de Fondo de Reparo"),
        ("A", "Garantía de Anticipo Financiero")
    )
	legacy_poliza_concepto = forms.ChoiceField(choices=CONCEPTO)
	legacy_poliza_fecha	= forms.DateField(input_formats=['%d/%m/%Y'], localize=True)
	
	class Meta:
		model = models.LegacyPoliza
		fields = "__all__"
		widgets = {
			"legacy_poliza_tomador" : EmpresaWidget
		}

class EmpresaForm(forms.ModelForm):
	class Meta:
		model = models.Empresa
		fields = "__all__"

class ObraForm(forms.ModelForm):
	class Meta:
		model = models.Obra
		fields = "__all__"
		widgets = {
			"obra_empresa" : EmpresaWidget
		}

class CertificadoForm(forms.ModelForm):
	class Meta:
		model = models.Certificado
		fields = "__all__"

class PolizaMovimientoForm(forms.ModelForm):
	class Meta:
		model = models.Poliza_Movimiento
		fields = "__all__"

carga/templates/crear-empresa.html
{% extends "base.html" %}

{% block content %}

<!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

{{ form.media.css }}

<div class="container">
<form action="{% url "carga:crear-empresa" %}" method="POST"> 

{% csrf_token %}
{{ form.errors }}
    <div class="row mx-md-n5"> {{form.empresa_nombre.label}} {{ form.empresa_nombre }} </div>
    <div class="row mx-md-n5"> {{form.empresa_cuit.label}} {{ form.empresa_cuit }} </div>
    <div class="row mx-md-n5"> {{form.empresa_titular_titulo.label}} {{ form.empresa_titular_titulo }} </div>
    <div class="row mx-md-n5"> {{form.empresa_titular_nombre.label}} {{form.empresa_titular_nombre}}</div>
    <div class="row mx-md-n5"> {{form.empresa_titular_dni.label}} {{form.empresa_titular_dni}} </div>
    <div class="row mx-md-n5"> {{form.empresa_direccion.label}} {{ form.empresa_direccion }} </div>
    <div class="row mx-md-n5"> {{form.empresa_inscripcion.label}} {{ form.empresa_inscripcion }} </div>
    <div class="row mx-md-n5"> {{form.empresa_correo_p.label}} {{ form.empresa_correo_p }} </div>
    <div class="row mx-md-n5"> {{form.empresa_correo_s.label}} {{ form.empresa_correo_s }} </div>
<input type='submit' value='Guardar' class="btn" />
</form>
</div>

{{ form.media.js }}

<script>
$(function () {
    $.datetimepicker.setLocale('es');
    $("#id_poliza_fecha").datetimepicker({
    timepicker:false,
    format: 'd/m/Y',
    });
  });
$('select').select2().on("select2-close", function () {
    setTimeout(function() {
        $('.select2-container-active').removeClass('select2-container-active');
        $(':focus').blur(); 
    }, 1);
});
</script>



{% endblock %}

carga/templates/crear-movimiento-poliza.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <form action="{% url "carga:crear-poliza-movimiento"%}" method="POST">
        {% csrf_token %}
        {{ form.errors }}

        {% for field in form %}
            <div class="row mx-md-n5"> {{field.label}} {{field}} </div>
            {% endfor %}
            <input type="submit" value="Guardar" class="btn" />
    </form>
</div>

<script>
    $('select').select2().on("select2-close", function () {
        setTimeout(function() {
            $('.select2-container-active').removeClass('select2-container-active');
            $(':focus').blur(); 
        }, 1);
    });
</script>

{% endblock %}

carga/templates/estado-poliza.html
{% extends "base.html" %}

{% block content %}

<!-- <form action="{% url "carga:estado-poliza" object.id %}" method="POST"> 

    {% csrf_token %}
-->
<div class="container-fluid">
<div class="row">
<div class="col">
    <p class="poliza-e-p"><b>ID: </b>{{object.id}}</p>
    <p class="poliza-e-p"><b>Fecha de Carga: </b>{{object.poliza_fecha}}</p>
    <p class="poliza-e-p"><b>Número de Actuación: </b>{{object.poliza_expediente}}</p>
    <p class="poliza-e-p"><b>Número de Póliza: </b>{{object.poliza_numero}}</p>
    <p class="poliza-e-p"><b>Concepto: </b>{{object.get_poliza_concepto_display}}</p>
    <p class="poliza-e-p"><b>Anexo: </b>{{object.poliza_anexo}}</p>
    <p class="poliza-e-p"><b>Número de Recibo: </b>{{object.poliza_recibo}}</p>
    <p class="poliza-e-p"><b>Aseguradora: </b>{{object.poliza_aseguradora}}</p>
    <p class="poliza-e-p"><b>Tomador: </b>{{object.poliza_tomador}}</p>
    <p class="poliza-e-p"><b>Monto Asegurado en Pesos: </b>${{object.poliza_monto_pesos}}</p>
    <p class="poliza-e-p"><b>Monto Asegurado en UVIs: </b>{{object.poliza_monto_uvi}} (UVI)</p>
</div>
<div class="col">
    <p class="poliza-e-p"><b><u>Obra: </u></b></p>
    <p class="poliza-e-p"><b>Programa: </b>{{object.poliza_obra.obra_programa}}</p>
    <p class="poliza-e-p"><b>Convenio: </b>{{object.poliza_obra.obra_convenio}}</p>
    <p class="poliza-e-p"><b>Expediente Madre: </b>{{object.poliza_obra.obra_expediente}}</p>
    <p class="poliza-e-p"><b>Resolución de Adjudicación: </b>N°{{object.poliza_obra.obra_resolucion}}</p>
    <p class="poliza-e-p"><b>Firma de Contrato: </b>{{object.poliza_obra.obra_fecha_contrato}}</p>
    <p class="poliza-e-p"><b>Nombre: </b>{{object.poliza_obra.obra_nombre}}</p>
    <p class="poliza-e-p"><b>Compulsa: </b>{{object.poliza_obra.get_obra_licitacion_tipo_display}} N°{{object.poliza_obra.obra_licitacion_numero}}/{{object.poliza_obra.obra_licitacion_ano}}</p>
    <p class="poliza-e-p"><b>Monto Contrato(Pesos): </b>${{object.poliza_obra.obra_contrato_total_pesos}}</p>
    <p class="poliza-e-p"><b>Monto Contrato(UVI): </b>{{object.poliza_obra.obra_contrato_total_uvi}}</p>
</div>
</div>
<a style="float: right" href="{% url "carga:crear-poliza-movimiento"%}"><img src="/static/clipboard-plus.svg" alt="Editar" width="30" heigth="30 /"></a>
<table class="table table-striped table-hover border border-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Fecha</th>
            <th scope="col">Receptor</th>
            <th scope="col">Area</th>
            <th scope="col">Enviado por:</th>
            <th scope="col">Editar</th>
        </tr>
    </thead>
    <tbody>
        {% for instance in object.poliza_movimiento_set.all %}
        <tr>
            <th scope="row">{{instance.id}}</th>
            <th scope="row">{{instance.poliza_movimiento_fecha|date:"d-m-Y"}}</th>
            <td>{{instance.poliza_movimiento_receptor}}</td>
            <td>{{instance.poliza_movimiento_area}}</td>
            <td>{{instance.poliza_movimiento_editor}}</td>
            <td><a href="{% url "carga:update-poliza-movimiento" instance.id %}"><img src="/static/edit.png" alt="Editar" width="30" heigth="30 /"></a><a href="{% url "carga:imprimir-poliza-movimiento" instance.id %}"><img src="/static/print.png" alt="Editar" width="30" heigth="30 /"></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

carga/templates/legacy-crear-poliza.html
{% extends "base.html" %}

{% block content %}

<!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

{{ form.media.css }}

<div class="container">
<form action="{% url "carga:legacy-crear-poliza" %}" method="POST"> 

{% csrf_token %}
{{ form.errors }}

{% for field in form %}
  <div class="row mx-md-n5"> {{field.label}} {{ field }} </div>
{% endfor %}
<input type='submit' value='Guardar' class="btn" />
</form>
</div>

{{ form.media.js }}

<script>
$(function () {
    $.datetimepicker.setLocale('es');
    $("#id_poliza_fecha").datetimepicker({
    timepicker:false,
    format: 'd/m/Y',
    });
  });
$('select').select2().on("select2-close", function () {
    setTimeout(function() {
        $('.select2-container-active').removeClass('select2-container-active');
        $(':focus').blur(); 
    }, 1);
});
</script>



{% endblock %}

carga/templates/legacy-update-poliza.html
{% extends "base.html" %}

{% block content %}

<!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

{{ form.media.css }}

<div class="container">
<form action="{% url "carga:legacy-update-poliza" object.id %}" method="POST"> 

{% csrf_token %}
{{ form.errors }}

{% for field in form %}
    <div class="row mx-md-n5"> {{field.label}} {{field}} </div>
{% endfor %}
    <input type='submit' value='Guardar' />
</form>
<!--
<div class="row mx-md-n5"> {{form.poliza_fecha.label}} {{ form.poliza_fecha }} </div>
<div class="row mx-md-n5"> {{form.poliza_expediente.label}} {{ form.poliza_expediente }} </div>
<div class="row mx-md-n5"> {{form.poliza_receptor.label}} {{ form.poliza_receptor }} </div>
<div class="row mx-md-n5"> {{form.poliza_area.label}} {{ form.poliza_area }} </div>
<div class="row mx-md-n5"> {{form.poliza_numero.label}} {{ form.poliza_numero }} </div>
<div class="row mx-md-n5"> {{form.poliza_concepto.label}} {{ form.poliza_concepto }} </div>
<div class="row mx-md-n5"> {{form.poliza_anexo.label}} {{ form.poliza_anexo }} </div>
<div class="row mx-md-n5"> {{form.poliza_recibo.label}} {{ form.poliza_recibo }} </div>
<div class="row mx-md-n5"> {{form.poliza_aseguradora.label}} {{ form.poliza_aseguradora }} </div>
<div class="row mx-md-n5"> {{form.poliza_tomador.label}} {{ form.poliza_tomador }} </div>
<div class="row mx-md-n5"> {{form.poliza_obra_nombre.label}} {{ form.poliza_obra_nombre }} </div>
<div class="row mx-md-n5"> {{form.poliza_obra_convenio.label}} {{ form.poliza_obra_convenio }} </div>
<div class="row mx-md-n5"> {{form.poliza_obra_expediente.label}} {{ form.poliza_obra_expediente }} </div>
<div class="row mx-md-n5"> {{form.poliza_monto_pesos.label}} {{ form.poliza_monto_pesos }} </div>
<div class="row mx-md-n5"> {{form.poliza_monto_uvi.label}} {{ form.poliza_monto_uvi }} </div>
-->
</div>

{{ form.media.js }}

<script>
$(function () {
    $.datetimepicker.setLocale('es');
    $("#id_poliza_fecha").datetimepicker({
    timepicker:false,
    format: 'd/m/Y',
    });
  });
$('select').select2().on("select2-close", function () {
    setTimeout(function() {
        $('.select2-container-active').removeClass('select2-container-active');
        $(':focus').blur(); 
    }, 1);
});
</script>



{% endblock %}