api/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from rest_framework.routers import DefaultRouter

from carga import views, models
from api import views as restviews

app_name = "api"

router = DefaultRouter()
router.register(r"legacy_polizas", restviews.LegacyPolizaViewSet)
router.register(r"polizas", restviews.PolizaViewset)
router.register(r"empresas", restviews.EmpresaViewSet)
router.register(r"obras", restviews.ObraViewSet)
router.register(r"certificados", restviews.CertificadoViewSet)

urlpatterns = [
	url(r"^api/", include(router.urls)),
	url("polizas/", restviews.listapolizas, name="polizas"),
	url("legacy_polizas_dt/", restviews.index, name="legacy_polizas"),
	url("empresas/", restviews.listaempresas, name="empresas"),
	url("obras/", restviews.listaobras, name="obras"),
	url("certificados/", restviews.listacertificados, name="certificados")
	#path("test/<pk>", restviews.PolizaDetail.as_view(), name="profile-detail")
]

# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from snippets import views

# # Crear Router y registrar los viewsets
# router = DefaultRouter()
# router.register(r"snippets", views.SnippetViewSet)
# router.register(r"user", views.UserViewSet)

# urlpatterns = [
#     path("", include(router.urls))
# ]

carga/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from carga import views, models

app_name = "carga"

urlpatterns = [
	#path("imprimir/<pk>", views.ImprimirLegacyPoliza.as_view(), name="imprimir-poliza"),
	#path("update/<pk>", views.UpdateLegacyPoliza.as_view(), name="update"),
	#path("crear/poliza/", views.CrearLegacyPoliza.as_view(), name="legacy-crear-poliza"),
	path("crear/empresa/", views.CrearEmpresa.as_view(), name="crear-empresa"),
	path("crear/empresa/<pk>", views.UpdateEmpresa.as_view(), name="update-empresa"),
]
certificado_patterns = [
	path("crear/certificado/", views.CrearCertificado.as_view(), name="crear-certificado"),
	path("crear/certificado/<pk>", views.UpdateCertificado.as_view(), name="update-certificado"),
	path("crear/certificado/detalle/<pk>", views.CertificadoView.as_view(), name="detalle-certificado")
]
obra_patterns = [
	path("crear/obra/", views.CrearObra.as_view(), name="crear-obra"),
	path("crear/obra/<pk>", views.UpdateObra.as_view(), name="update-obra"),
	path("crear/obra/estado/<pk>", views.EstadoObra.as_view(), name = "estado-obra"),
]
poliza_patterns = [
	path("crear/poliza/", views.CrearPoliza.as_view(), name="crear-poliza"),
	path("crear/poliza/<pk>", views.UpdatePoliza.as_view(), name="update-poliza"),
	path("crear/poliza/estado/<pk>", views.EstadoPoliza.as_view(), name="estado-poliza"),
]
movimiento_patterns = [
	path("crear/poliza/movimiento/", views.CrearPolizaMovimiento.as_view(), name="crear-poliza-movimiento"),
	path("crear/poliza/movimiento/<pk>", views.UpdatePolizaMovimiento.as_view(), name="update-poliza-movimiento"),
	path("crear/poliza/movimiento/imprimir/<pk>", views.ImprimirPolizaMovimiento.as_view(), name="imprimir-poliza-movimiento"),

]
legacy_patterns = [
	path("crear/legacy_poliza/", views.CrearLegacyPoliza.as_view(), name="legacy-crear-poliza"),
	path("legacy_imprimir/<pk>", views.ImprimirLegacyPoliza.as_view(), name="legacy-imprimir-poliza"),
	path("legacy_update/<pk>", views.UpdateLegacyPoliza.as_view(), name="legacy-update-poliza"),
]

urlpatterns += certificado_patterns
urlpatterns += legacy_patterns
urlpatterns += poliza_patterns
urlpatterns += movimiento_patterns
urlpatterns += obra_patterns

polizador/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", auth_views.LoginView.as_view(redirect_authenticated_user=True, redirect_field_name="polizas")),
    path("accounts/", include('django.contrib.auth.urls')),
    path("polizas/", include("carga.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls"))
]

templates/base.html
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="shortcut icon" href="{%  static '/favicon.ico' %}">
  <link href="{% static "style.css" %}" rel="stylesheet">
  <!-- Bootstrap & Popper JS-->
  <link rel="stylesheet" type="text/css" href="{% static "/Bootstrap5/css/bootstrap.min.css" %}">
  <script src="{% static "/Bootstrap5/js/bootstrap.bundle.min.js" %}"></script>
  <!-- DataTables -->
	<link rel="stylesheet" type="text/css" href="{% static "/DataTables/DataTables-1.11.5/css/dataTables.bootstrap5.min.css" %}">
  <script type="text/javascript" charset="utf8" src="{% static "/DataTables/datatables.min.js" %}"></script>
  <!-- YADCF & Ellipsis -->
  <script type="text/javascript" charset="utf8" src="{% static "/DataTables/yadcf-ellipsis.js" %}"></script>
  <!-- Select2 plugin CSS -->
	<link rel="stylesheet" type="text/css" href="{% static "/select2/select2.min.css" %}">
	<!-- Select2 plugin JS -->
	<script src="{% static "/select2/select2.min.js" %}"></script>
  <!-- Moment.js -->
  <script src="{% static "/moment/moment.js" %}"></script>
  <script src="{% static "/moment/es.js" %}"></script>
  <script src="{% static "/moment/datetime.js" %}"></script>
  
  
<title>Polizador V3.0</title>

</head>
<body>
<div class="d-print-none">
	{% include "navbar.html" %}
</div>

<div>
	{% block content %}
	Contenido dinámico
	{% endblock %}
</div>


</body>
</html>

templates/lista-certificados.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
      <table id="lista-certificados" class="table table-striped table-bordered align-middle" style="width:100%">
          <thead>
              <tr>
                <th> ID </th>
                <th> Programa </th>
                <th> Convenio </th>
                <th> Empresa </th>
                <th> Soluciones </th>
                <th> Obra </th>
                <th> Localidad </th>
                <th> Expediente </th>
                <th> AntN° </th>
                <th> ObN° </th>
                <th> DevN° </th>
                <th> Periodo </th>
                <th> Monto Pesos </th>
                <th> Mes % </th>
                <th> Anterior % </th>
                <th> Acumulado % </th>
                <th> Financiamiento </th>
                <th> Monto Devolucion </th>
                <th> Monto a Cobrar </th>
                <th> Monto UVI </th>
                <th> Acciones </th>
                
              </tr>
          </thead>
          <tfoot>
            <tr>
                <th> ID </th>
                <th> Programa </th>
                <th> Convenio </th>
                <th> Empresa </th>
                <th> Soluciones </th>
                <th> Obra </th>
                <th> Localidad </th>
                <th> Expediente </th>
                <th> AntN° </th>
                <th> ObN° </th>
                <th> DevN° </th>
                <th> Periodo </th>
                <th> Monto Pesos </th>
                <th> Mes % </th>
                <th> Anterior % </th>
                <th> Acumulado % </th>
                <th> Financiamiento </th>
                <th> Monto Devolucion </th>
                <th> Monto UVI </th>
                <th> Monto a Cobrar </th>
                <th> Acciones </th>
                
            </tr>
        </tfoot>
      </table>
</div>

<script>
$(document).ready( function() {
  var TableCertificado = $('#lista-certificados').DataTable({
    serverSide: true,
    processing: true,
    scrollX: true,
    dom: '<fl<t>ip>B',
      buttons: [
        {extend: 'excel', text: "Exportar a Excel"}
    ],
    lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "All"]],
    "language": {"url": 'https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-AR.json'},
    "ajax": { "url": '/api/api/certificados/?format=datatables', "format": "GET", },
    order: [[12, "desc"]],
    columnDefs: [
    {
      "className": "dt-center", "targets": "_all" 
    },
    {"targets": -1, "data": "id", "render": function ( data, type, row, meta ) 
		{ return '<a href="/polizas/crear/certificado/'+data+'"><img src="/static/edit.png" title="Editar" width="30" heigth="30 /"></a> <a href="/polizas/crear/certificado/detalle/'+data+'"><img src="/static/print.png" title="Detalle" width="30" heigth="30 /"></a>'
    ;} },
    {
      targets: 5,
      render: $.fn.dataTable.render.ellipsis(50),
    },
  //  {targets: 5, data:"certificado_obra.id", render: function(data, type, row, meta)
  //  { return data }  }
    ],
    "columns": [
            {"data": "id", searchable: false},
            {"data": "certificado_obra.obra_programa.programa_nombre", "name": "certificado_obra.obra_programa.programa_nombre", orderable: false},
            {"data": "certificado_obra.obra_convenio", "name": "certificado_obra.obra_convenio", orderable: false},
            {"data": "certificado_obra.obra_empresa.empresa_nombre", "name": "certificado_obra.obra_empresa.empresa_nombre", orderable: false},
            {"data": "certificado_obra.obra_soluciones", "name": "certificado_obra.obra_soluciones", searchable: false, orderable: false},
            {"data": "certificado_obra.obra_nombre", "name": "certificado_obra.obra_nombre", orderable: false},
            {"data": "certificado_obra.obra_localidad.localidad_nombre", "name": "certificado_obra.obra_localidad.localidad_nombre"},
            {"data": "certificado_expediente", orderable: false},
            {"data": "certificado_rubro_anticipo", orderable: false},
            {"data": "certificado_rubro_obra", orderable: false},
            {"data": "certificado_rubro_devanticipo", orderable: false},
            {"data": "certificado_fecha", 
              render: $.fn.dataTable.render.moment("YYYY-MM-DD","MMMM/YY","es")
          },
            {"data": "certificado_monto_pesos",
            'render': function (certificado_monto_pesos) {  
              return '$' + certificado_monto_pesos;
              }, searchable: false, orderable: false},
            {"data": "certificado_mes_pct",
            'render': function (certificado_mes_pct) {  
              return certificado_mes_pct + "%";
              }, searchable: false, orderable: false},
            {"data": "certificado_ante_pct",
            'render': function (certificado_ante_pct) {  
              return certificado_ante_pct + "%";
              }, searchable: false, orderable: false},
            {"data": "certificado_acum_pct",
            'render': function (certificado_acum_pct) {  
              return certificado_acum_pct + "%";
              }, searchable: false, orderable: false},
            {"data": "certificado_financiamiento", orderable: false},
            {"data": "certificado_devolucion_monto",
            'render': function (certificado_devolucion_monto) {  
              return '$' + certificado_devolucion_monto;
              }, searchable: false, orderable: false},
            {"data": "certificado_monto_cobrar",
            'render': function (certificado_monto_cobrar) {  
              return '$' + certificado_monto_cobrar;
              }, searchable: false, orderable: false},
              {"data": "certificado_monto_uvi", searchable: false, orderable: false},
              {"data": "id", searchable: false, orderable: false},
            ]
      });
      TableCertificado.buttons().container()
    .appendTo( $('.col-sm-6:eq(0)', TableCertificado.table().container() ) );
      });
</script>

{% endblock %}

templates/lista-empresas.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
      <table id="lista-empresas" class="table table-striped table-bordered align-middle" style="width:100%">
          <thead>
              <tr>
                <th> ID </th>
                <th> Nombre </th>
                <th> CUIT </th>
                <th> Titular </th>
                <th> Caracter </th>
                <th> DNI </th>
                <th> Dirección </th>
                <th> Correo Primario </th>
                <th> Correo Secundario </th>
                <th> Registro </th>
                <th> Acciones </th>
              </tr>
          </thead>
          <tfoot>
            <tr>
              <th> ID </th>
              <th> Nombre </th>
              <th> CUIT </th>
              <th> Titular </th>
              <th> Caracter </th>
              <th> DNI </th>
              <th> Dirección </th>
              <th> Correo Primario </th>
              <th> Correo Secundario </th>
              <th> Registro </th>
              <th> Acciones </th>
            </tr>
        </tfoot>
      </table>
</div>
</thead>

<script>
$(document).ready( function() {
    'use strict';
    var TableEmpresa;
    TableEmpresa = $('#lista-empresas').DataTable({
		serverSide: true,
    processing: true,
    scrollX: true,
    dom: '<fl<t>ip>B',
      buttons: [
        {extend: 'excel', text: "Exportar a Excel"}
    ],
    lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "All"]],
    "language": {"url": 'https://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json'},
		"ajax": {"url": "/api/api/empresas/?format=datatables"},
		columnDefs: [{"targets": -1, "data": "id", "render": function ( data, type, row, meta ) 
		{ return '<a href="/polizas/crear/empresa/'+data+'"><img src="/static/edit.png" title="Editar" width="30" height="30" /></a>';} }],
    columns: [
      {"data": "id", searchable: false},
      {"data": "empresa_nombre"},
      {"data": "empresa_cuit"},
      {"data": "empresa_titular_nombre"},
      {"data": "empresa_titular_titulo"},
      {"data": "empresa_titular_dni"},
      {"data": "empresa_direccion"},
      {"data": "empresa_correo_p"},
      {"data": "empresa_correo_s"},
      {"data": "empresa_inscripcion"},
      {"data": "id", searchable: false},
    ],
    });
    TablePoliza.buttons().container()
    .appendTo( $('.col-sm-6:eq(0)', TablePoliza.table().container() ) );
    //yadcf.init(TableEmpresa, [
    //    {
    //      column_number: 1,
		//			filter_type: "select",
    //      filter_default_label: "Filtrar"
    //    },
    //    {
    //      column_number: 2,
    //      filter_type: "select",
    //      filter_default_label: "Filtrar"
    //    }
    //    ],
    //    "footer",
    //    );
});
</script>

{% endblock %}

templates/lista-legacy-polizas.html
{% extends "base.html" %}
{% block content %}

<div class="container-fluid">
      <table id="lista-polizas" class="table table-striped table-bordered align-middle" style="width:100%">
          <thead>
              <tr>
                <th> Acciones </th>
                <th> Fecha </th>
                <th> Receptor </th>
                <th> Area </th>
                <th> Expediente </th>
                <th> Concepto de Póliza </th>
                <th> Número de Póliza </th>
                <th> Anexo de Póliza </th>
                <th> Recibo de Pago </th>
                <th> Entidad Aseguradora </th>
                <th> Obra </th>
                <th> Empresa/Tomador </th>
                <th> Monto Sustituido(Pesos) </th>
                <th> Monto Sustituido(UVI) </th>
                <th> Convenio Específico </th>
                <th> Expediente de Obra </th>
                <th> Editor </th>
                <th> Ultimo Editor </th>
              </tr>
          </thead>
          <tfoot>
            <tr>
              <th> Acciones </th>
              <th> Fecha </th>
              <th> Receptor </th>
              <th> Area </th>
              <th> Expediente </th>
              <th> Concepto de Póliza </th>
              <th> Número de Póliza </th>
              <th> Anexo de Póliza </th>
              <th> Recibo de Pago </th>
              <th> Entidad Aseguradora </th>
              <th> Obra </th>
              <th> Empresa/Tomador </th>
              <th> Monto Sustituido(Pesos) </th>
              <th> Monto Sustituido(UVI) </th>
              <th> Convenio Específico </th>
              <th> Expediente de Obra </th>
              <th> Editor </th>
              <th> Ultimo Editor </th>
            </tr>
        </tfoot>
      </table>
</div>

<script>
  $(document).ready( function() {
      'use strict';
      var TablePoliza
      TablePoliza = $('#lista-polizas').DataTable({
      serverSide: true,
      processing: true,
      scrollX: true,
      dom: '<fl<t>ip>B',
        buttons: [
          {extend: 'excel', text: "Exportar a Excel"}
      ],
      order: [[0, "desc"]],
      lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "All"]],
      "language": {"url": 'https://cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json'},
      "ajax": {"url": "/api/api/legacy_polizas/?format=datatables"},
      columnDefs: [{"targets": 0, "data": "id", "render": function ( data, type, row, meta ) 
		{ return '<a href="/polizas/legacy_update/'+data+'"><img src="/static/edit.png" title="Editar" width="30" height="30"/></a><a href="/polizas/legacy_imprimir/'+data+'"><img src="/static/print.png" title="Imprimir" width="30" height="30"/></a>';} }],
      columns: [
        {"data":"id", searchable: false, orderable: false},
        {"data":"legacy_poliza_fecha"},
        {"data":"legacy_poliza_receptor.receptor_nombre", "name":"legacy_poliza_receptor.receptor_nombre", searchable: false, orderable: false},
        {"data":"legacy_poliza_area.area_nombre", "name":"legacy_poliza_area.area_nombre", orderable: false},
        {"data":"legacy_poliza_expediente", orderable: false},
        {"data":"legacy_poliza_concepto", searchable: false, orderable: false},
        {"data":"legacy_poliza_numero"},
        {"data":"legacy_poliza_anexo", searchable: false, orderable: false},
        {"data":"legacy_poliza_recibo"},
        {"data":"legacy_poliza_aseguradora.aseguradora_nombre", "name":"legacy_poliza_aseguradora.aseguradora_nombre", orderable: false},
        {"data":"legacy_poliza_obra_nombre"},
        {"data":"legacy_poliza_tomador.empresa_nombre", "name":"legacy_poliza_tomador.empresa_nombre"},
        {"data":"legacy_poliza_monto_pesos", 'render': function (legacy_poliza_monto_pesos) {  
          return '$' + legacy_poliza_monto_pesos;
          }, searchable: false, orderable: false},
        {"data":"legacy_poliza_monto_uvi"},
        {"data":"legacy_poliza_obra_convenio"},
        {"data":"legacy_poliza_obra_expediente"},
        {"data":"legacy_poliza_creador", searchable: false},
        {"data":"legacy_poliza_editor", searchable: false},
      ],
    });
    TablePoliza.buttons().container()
    .appendTo( $('.col-sm-6:eq(0)', TablePoliza.table().container() ) );
    yadcf.init(TablePoliza, [
        {
          // Fecha
          column_number: 1,
          filter_type: "select",
          filter_default_label: "Filtrar",
        },
        {
          // Area
          column_number: 3,
          filter_type: "select",
          filter_default_label: "Filtrar"
        },
        {
          // Aseguradora
          column_number: 9,
          filter_type: "select",
          filter_default_label: "Filtrar"
        },
        {
          // Empresa
          column_number: 13,
          filter_type: "select",
          filter_default_label: "Filtrar"
        },
        ],
        "footer",
        );
});
  </script>

{% endblock %}

templates/navbar copy.html
<script type="text/javascript">
	window.addEventListener("resize", function() {
		"use strict"; window.location.reload(); 
	});

	document.addEventListener("DOMContentLoaded", function(){
        
		// make it as accordion for smaller screens
		if (window.innerWidth < 992) {

			// close all inner dropdowns when parent is closed
			document.querySelectorAll('.navbar .dropdown').forEach(function(everydropdown){
				everydropdown.addEventListener('hidden.bs.dropdown', function () {
					// after dropdown is hidden, then find all submenus
					  this.querySelectorAll('.submenu').forEach(function(everysubmenu){
					  	// hide every submenu as well
					  	everysubmenu.style.display = 'none';
					  });
				})
			});
			
			document.querySelectorAll('.dropdown-menu a').forEach(function(element){
				element.addEventListener('click', function (e) {
		
				  	let nextEl = this.nextElementSibling;
				  	if(nextEl && nextEl.classList.contains('submenu')) {	
				  		// prevent opening link if link needs to open dropdown
				  		e.preventDefault();

				  		if(nextEl.style.display == 'block'){
				  			nextEl.style.display = 'none';
				  		} else {
				  			nextEl.style.display = 'block';
				  		}

				  	}
				});
			})
		}
		// end if innerWidth

	}); 
	// DOMContentLoaded  end
</script>

<!-- ============= COMPONENT ============== -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark d-print-none">
 <div class="container-fluid">
 	 <span class="navbar-brand">ICDUP</span>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav"  aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="main_nav">
	

	<ul class="navbar-nav">
		<li class="nav-item active"> <a class="nav-link" href="{% url "api:polizas" %}">Home </a> </li>
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">  Listados  </a>
		    <ul class="dropdown-menu">
			  <li><a class="dropdown-item" href="{% url "api:polizas" %}"> Listar Pólizas </a></li>
			  <li><a class="dropdown-item" href="{% url "api:empresas" %}"> Listar Empresas </a></li>
			  <li><a class="dropdown-item" href="{% url "api:obras" %}"> Listas Obras </a></li>
			  <li><a class="dropdown-item" href="{% url "api:certificados" %}"> Lista Certificados </a> </li>
		    </ul>
		</li>
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">  Crear Nuevo  </a>
		    <ul class="dropdown-menu">
				<li><a class="dropdown-item" href="{% url "carga:crear-poliza" %}"> Crear Póliza </a></li>
				<li><a class="dropdown-item" href="{% url "carga:crear-empresa" %}"> Crear Empresa </a></li>
				<li><a class="dropdown-item" href="{% url "carga:crear-obra" %}"> Crear Obra </a></li>
				<li><a class="dropdown-item" href="{% url "carga:crear-certificado" %}"> Crear Certificado </a></li>
		    </ul>
		</li>
		</ul>

	<ul class="navbar-nav ms-auto">
				
		{% if request.user.is_authenticated %}
		<li class="nav-item dropdown">
			<a class="nav-link  dropdown-toggle" href="#" data-bs-toggle="dropdown"> {{ request.user.first_name }} {{request.user.last_name }} </a>
		    <ul class="dropdown-menu dropdown-menu-right">
			  <li><a class="dropdown-item" href="{% url "logout" %}"> Salir </a></li>
			</ul>
		</li>
		{% else %}
		<li class="nav-item"><a class="nav-link" href="{% url "login" %}"> Ingresar </a></li>
		{% endif %}

	
<!--		<li class="nav-item dropdown">
			<a class="nav-link  dropdown-toggle" href="#" data-bs-toggle="dropdown"> Dropdown right </a>
		    <ul class="dropdown-menu dropdown-menu-right">
			  <li><a class="dropdown-item" href="#"> Dropdown item 1</a></li>
			  <li><a class="dropdown-item" href="#"> Dropdown item 2 </a></li>
			  <li><a class="dropdown-item" href="#"> Dropdown item 3 &raquo; </a>
			  	 <ul class="submenu submenu-left dropdown-menu">
				    <li><a class="dropdown-item" href="">Submenu item 1</a></li>
				    <li><a class="dropdown-item" href="">Submenu item 2</a></li>
				    <li><a class="dropdown-item" href="">Submenu item 3</a></li>
				    <li><a class="dropdown-item" href="">Submenu item 4</a></li>
				 </ul>
			  </li>
			  <li><a class="dropdown-item" href="#"> Dropdown item 4 </a></li>
		    </ul>
		</li> -->
	</ul>

  </div> <!-- navbar-collapse.// -->
 </div> <!-- container-fluid.// -->
</nav>

templates/navbar.html
<!-- Barra de naufragación -->
<nav class="navbar navbar-expand-lg navbar-light d-print-none">
	<div class="container-fluid">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainnavbar">
		  <span class="navbar-toggler-icon"></span>
		</button>
  
		<div class="collapse navbar-collapse justify-content-md-center" id="mainnavbar">
		  <ul class="navbar-nav">
			<li class="nav-item dropdown">
				<a class="nav-link active dropdown-toggle" href="#" id="dropdown-listas" data-bs-toggle="dropdown" aria-expanded="false">Listados</a>
				<ul class="dropdown-menu" aria-labelledby="dropdown-listas">
				  <li><a class="dropdown-item" href="{% url "api:legacy_polizas" %}">Legacy Pólizas</a></li>
				  <li><a class="dropdown-item" href="{% url "api:polizas" %}">Listar Pólizas</a></li>
				  <li><a class="dropdown-item" href="{% url "api:empresas" %}">Listar Empresas</a></li>
				  <li><a class="dropdown-item" href="{% url "api:obras" %}">Listar Obras</a></li>
				  <li><a class="dropdown-item" href="{% url "api:certificados" %}">Listar Certificados</a></li>
				</ul>
			  </li>
			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url "carga:legacy-crear-poliza" %}">Cargar Póliza VIEJO</a>
			</li>
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="{% url "carga:crear-poliza" %}">Cargar Póliza</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url "carga:crear-empresa" %}">Cargar Empresa</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link active" aria-current="page" href="{% url "carga:crear-obra" %}">Cargar Obra</a>
			</li>
			<li class="nav-item">
				<a class="nav-link active" aria-current="page" href="{% url "carga:crear-certificado" %}">Cargar Certificado</a>
			</li>
			{% if request.user.is_authenticated %}
			<li class="nav-item dropdown">
				<a class="nav-link  dropdown-toggle" href="#" data-bs-toggle="dropdown"> {{ request.user.first_name }} {{request.user.last_name }} </a>
				<ul class="dropdown-menu">
				  <li><a class="dropdown-item" href="{% url "logout" %}"> Salir </a></li>
				</ul>
			</li>
			{% else %}
			<li class="nav-item"><a class="nav-link" href="{% url "login" %}"> Ingresar </a></li>
			{% endif %}
		  </ul>
	  </div>
</nav>